# Application Name
spring.application.name=Apollo

# Database Configuration
spring.datasource.url=jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.shzfpsvdewmvughchoun
spring.datasource.password=Apollolibrary@2025


# Server Configuration
server.servlet.context-path=/api/v1

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL Queries in CLI
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true

# Error Handling
server.error.include-message=always
server.error.include-stacktrace=always

# Logging Configuration
logging.file.name=logs/apollo.log
logging.level.lk.apollo.security=DEBUG

# Supabase Configuration
supabase.url=https://shzfpsvdewmvughchoun.supabase.co
supabase.api-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoemZwc3ZkZXdtdnVnaGNob3VuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTU1NDI0MiwiZXhwIjoyMDU3MTMwMjQyfQ.8I3fRyzWJH_ZxvqWmJYkysLRh6A0P1itgU_uxXkTzok
supabase.jwt-secret=gPFaeiDLqnjhp0wC/j6h8XhNIsDIVpGqp24JoSg9ivA4jg5xL2pUFDqdxMi4GtKgXbBtBBrJdWFbMkxfLXmnXw==

# CORS Configuration
security.allowed-origins=http://localhost:5173,https://apollolib.vercel.app/,https://apollolibr.vercel.app/,https://apollolp.vercel.app/

# Swagger API Docs Path
springfox.documentation.swagger.v2.path=/v2/api-docs
